// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYhFZ90pmE3MfIAw9pTl9UtIYDxALTZwo',
    appId: '1:631593988476:web:7e102109c9552935fc34f9',
    messagingSenderId: '631593988476',
    projectId: 'dangomlife',
    authDomain: 'dangomlife.firebaseapp.com',
    storageBucket: 'dangomlife.appspot.com',
    measurementId: 'G-E19CZ9GSSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-frI87JFNbCjjzVcBr7uIxsdVFDJWsz0',
    appId: '1:631593988476:android:0ad86d909ff3e2e9fc34f9',
    messagingSenderId: '631593988476',
    projectId: 'dangomlife',
    storageBucket: 'dangomlife.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLHcV0MVVuBggfRHR_RXszQfnHSYDyhh8',
    appId: '1:631593988476:ios:63666173ec7fa565fc34f9',
    messagingSenderId: '631593988476',
    projectId: 'dangomlife',
    storageBucket: 'dangomlife.appspot.com',
    iosBundleId: 'com.example.everytime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLHcV0MVVuBggfRHR_RXszQfnHSYDyhh8',
    appId: '1:631593988476:ios:63666173ec7fa565fc34f9',
    messagingSenderId: '631593988476',
    projectId: 'dangomlife',
    storageBucket: 'dangomlife.appspot.com',
    iosBundleId: 'com.example.everytime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYhFZ90pmE3MfIAw9pTl9UtIYDxALTZwo',
    appId: '1:631593988476:web:1add12f3cec65917fc34f9',
    messagingSenderId: '631593988476',
    projectId: 'dangomlife',
    authDomain: 'dangomlife.firebaseapp.com',
    storageBucket: 'dangomlife.appspot.com',
    measurementId: 'G-GJT41EDZZZ',
  );

}